{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.138.1004.0 (24.11)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Dim.City\",\"Dim.Date\",\"Dim.Stock_Item\",\"Fact.Stock_Holding\",\"Dim.Supplier\",\"Dim.Category\",\"Dim.Color\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      }
    ],
    "culture": "pl-PL",
    "cultures": [
      {
        "name": "pl-PL",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "0087461e-74af-445c-ac29-d0f9f9e18d69",
        "fromColumn": "Valid From",
        "fromTable": "Dim.City",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_0274852c-29b6-4c95-927a-978ef79a2264"
      },
      {
        "name": "79d0893c-7a97-44b8-9553-2dee9621caad",
        "fromColumn": "Valid To",
        "fromTable": "Dim.City",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a6365485-89b3-443e-813a-358c7256be62"
      },
      {
        "name": "8f7fdb9c-997e-4777-b722-ef9cecdfee74",
        "fromColumn": "Date",
        "fromTable": "Dim.Date",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_542427ae-981a-401c-8a73-c3f4814d107d"
      },
      {
        "name": "b1fe0bdb-c1ff-43cb-a5d7-738d6ac8675f",
        "fromColumn": "Valid From",
        "fromTable": "Dim.Stock_Item",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_43c04760-7e1c-4782-bd68-e56b14dcf4bb"
      },
      {
        "name": "9904e94f-a718-4cc0-ab48-06121bf25ccf",
        "fromColumn": "Valid From",
        "fromTable": "Dim.Supplier",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_da1d75ef-d80e-4d3a-9e90-1f338481d234"
      },
      {
        "name": "9259438b-8832-4ae9-a7c8-9a901b9b37a9",
        "fromColumn": "Valid To",
        "fromTable": "Dim.Supplier",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_d432e486-5164-49fe-9113-448518a0a78a"
      },
      {
        "name": "01c2b06d-561b-4217-9c0e-eaf3ac7e18be",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Stock Item Key",
        "fromTable": "Fact.Stock_Holding",
        "toColumn": "Stock Item Key",
        "toTable": "Dim.Stock_Item"
      },
      {
        "name": "181e61cb-141b-9cea-0049-ab065248a4d9",
        "fromColumn": "Color",
        "fromTable": "Dim.Stock_Item",
        "toColumn": "Color",
        "toTable": "Dim.Color"
      },
      {
        "name": "d1a5bbc2-23b1-ee69-d9af-ec50b5f7935e",
        "fromColumn": "WWI Stock Item ID",
        "fromTable": "Dim.Stock_Item",
        "toColumn": "WWI Stock Item ID",
        "toTable": "Dim.Category"
      },
      {
        "name": "678de496-5ffe-48cb-e04d-1ed5b72abc2f",
        "fromColumn": "Valid To",
        "fromTable": "Dim.Stock_Item",
        "toColumn": "Date",
        "toTable": "Dim.Date"
      }
    ],
    "sourceQueryCulture": "pl-PL",
    "tables": [
      {
        "name": "Dim.City",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Nawigacja"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "City Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1c956078-32f2-46e9-a87b-0ce56c035b62",
            "sourceColumn": "City Key",
            "summarizeBy": "count"
          },
          {
            "name": "WWI City ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "77073e55-62d2-45ad-a99e-52c4771a4614",
            "sourceColumn": "WWI City ID",
            "summarizeBy": "count"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "feb67fdd-1f6e-4083-8dcb-ecb44caa0d16",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "State Province",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ead77270-fa17-4f2b-a8bc-abc82951226f",
            "sourceColumn": "State Province",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6217920-5c1f-4b95-91ad-388b61f11bd0",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Continent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15c2245e-421f-4126-b482-87e30baf4d02",
            "sourceColumn": "Continent",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Territory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad7278ed-ddde-4c1a-ae30-d2385782882d",
            "sourceColumn": "Sales Territory",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "180cf0fb-365f-4115-ba6e-b7819e85eda7",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Subregion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e28cf38-2a95-48f8-ade1-08bf1cd26f61",
            "sourceColumn": "Subregion",
            "summarizeBy": "none"
          },
          {
            "name": "Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "763b7440-1477-4804-b9c7-e78124b90ecc",
            "sourceColumn": "Location",
            "summarizeBy": "none"
          },
          {
            "name": "Latest Recorded Population",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4c11cd8f-521d-4b55-bc0e-0444222edeb6",
            "sourceColumn": "Latest Recorded Population",
            "summarizeBy": "sum"
          },
          {
            "name": "Valid From",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "194126eb-45b7-40e5-8284-ab7c9544192d",
            "sourceColumn": "Valid From",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Odmiana",
                "defaultHierarchy": {
                  "hierarchy": "Hierarchia dat",
                  "table": "LocalDateTable_0274852c-29b6-4c95-927a-978ef79a2264"
                },
                "isDefault": true,
                "relationship": "0087461e-74af-445c-ac29-d0f9f9e18d69"
              }
            ]
          },
          {
            "name": "Valid To",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "d0c7f67c-5deb-499d-831c-d3ec04a37f2f",
            "sourceColumn": "Valid To",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Odmiana",
                "defaultHierarchy": {
                  "hierarchy": "Hierarchia dat",
                  "table": "LocalDateTable_a6365485-89b3-443e-813a-358c7256be62"
                },
                "isDefault": true,
                "relationship": "79d0893c-7a97-44b8-9553-2dee9621caad"
              }
            ]
          },
          {
            "name": "Lineage Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4ae6b413-9585-4846-8a43-89c1eb76a77d",
            "sourceColumn": "Lineage Key",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "c6b55c38-adec-498d-82da-b0135a426de6",
        "partitions": [
          {
            "name": "Dim.City",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = Sql.Databases(\"DESKTOP-FUKU640\\SQLEXPRESS\"),",
                "    WideWorldImportersDW = Źródło{[Name=\"WideWorldImportersDW\"]}[Data],",
                "    Dimension_City = WideWorldImportersDW{[Schema=\"Dimension\",Item=\"City\"]}[Data],",
                "    #\"Usunięto pierwsze wiersze\" = Table.Skip(Dimension_City,1)",
                "in",
                "    #\"Usunięto pierwsze wiersze\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_81dc3a3c-8408-4e43-a67c-2df4d852e191",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c185137b-d8b7-4837-95a6-9a2c69f11d3b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Rok",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0d8c5807-8069-4bcf-9e1e-908176c604bc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Numer miesiąca",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9865c1dd-e4ca-4b29-9c88-194f06342d23",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Miesiąc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ce768243-27de-4380-9c67-616fe4bdac70",
            "sortByColumn": "Numer miesiąca",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Numer kwartału",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([Numer miesiąca] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "68bdc852-f658-4d76-b55a-01fa6baeb08a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Kwartał",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [Numer kwartału]",
            "isHidden": true,
            "lineageTag": "4c32b80e-68c8-4cbd-a2d5-6bf6fa0effea",
            "sortByColumn": "Numer kwartału",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dzień",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3ac6e32b-733f-4167-ba98-0ed59f300e77",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarchia dat",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Rok",
                "column": "Rok",
                "lineageTag": "462a2627-c24b-41d2-9227-2f534e442a2c",
                "ordinal": 0
              },
              {
                "name": "Kwartał",
                "column": "Kwartał",
                "lineageTag": "d4fe6687-d80d-4615-8de6-df4c01c9421b",
                "ordinal": 1
              },
              {
                "name": "Miesiąc",
                "column": "Miesiąc",
                "lineageTag": "6ed356c3-f4b3-425d-b35a-38e4c1f28c11",
                "ordinal": 2
              },
              {
                "name": "Dzień",
                "column": "Dzień",
                "lineageTag": "c99df28b-88e4-49f1-8623-f78ea64fac62",
                "ordinal": 3
              }
            ],
            "lineageTag": "271bc21e-836a-4f4d-ae73-62c98b82b69b"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "3735ed5b-47e7-4726-9458-35d3ad69be7e",
        "partitions": [
          {
            "name": "DateTableTemplate_81dc3a3c-8408-4e43-a67c-2df4d852e191",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_0274852c-29b6-4c95-927a-978ef79a2264",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4b208d92-291d-46ce-a373-899d60d0c61c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Rok",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "25a6fe09-d4d7-4e79-88d4-091515789656",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Numer miesiąca",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ce5be96e-bd2a-4fb8-b1f9-e75c9b6d3699",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Miesiąc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "4e956057-439d-444d-bd7e-2be1a7e6c2c1",
            "sortByColumn": "Numer miesiąca",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Numer kwartału",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([Numer miesiąca] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "25a47935-0a9a-40ba-84c4-bcd35bdbac97",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Kwartał",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [Numer kwartału]",
            "isHidden": true,
            "lineageTag": "b54c7470-037e-412d-88b3-db2fbe7f2194",
            "sortByColumn": "Numer kwartału",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dzień",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "df51c5df-3b1b-44f8-8123-5c2cf837a741",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarchia dat",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Rok",
                "column": "Rok",
                "lineageTag": "937db43a-9dd9-42ef-8742-355a02d68b47",
                "ordinal": 0
              },
              {
                "name": "Kwartał",
                "column": "Kwartał",
                "lineageTag": "5df5ac98-56a6-4a0c-8176-ad6d53556807",
                "ordinal": 1
              },
              {
                "name": "Miesiąc",
                "column": "Miesiąc",
                "lineageTag": "4b21d0b9-1991-4ff9-9f7e-5ac28b7d9b0a",
                "ordinal": 2
              },
              {
                "name": "Dzień",
                "column": "Dzień",
                "lineageTag": "efdecd71-90b8-4256-87dd-688bef80fc28",
                "ordinal": 3
              }
            ],
            "lineageTag": "ad2dd114-dedd-4ec8-8e05-aabf6e80599a"
          }
        ],
        "isHidden": true,
        "lineageTag": "9fce15aa-d402-4cd4-aa23-b1e8778b777a",
        "partitions": [
          {
            "name": "LocalDateTable_0274852c-29b6-4c95-927a-978ef79a2264",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Dim.City'[Valid From])), 1, 1), Date(Year(MAX('Dim.City'[Valid From])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_a6365485-89b3-443e-813a-358c7256be62",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4eaadfca-cab9-4faa-bd8a-b8f513a629db",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Rok",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a084d3b8-c7e4-40a5-b118-f9b9a847e133",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Numer miesiąca",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b3c7dd9b-1844-4d2c-bc67-a0fdcfb2408f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Miesiąc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "1d6a2be1-f7af-4ebf-8a11-8aa111c99454",
            "sortByColumn": "Numer miesiąca",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Numer kwartału",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([Numer miesiąca] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a96d6376-3699-4e99-8395-aaaa8f2dd6d1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Kwartał",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [Numer kwartału]",
            "isHidden": true,
            "lineageTag": "514b9ced-89f8-4b98-bd9a-8b3db945b493",
            "sortByColumn": "Numer kwartału",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dzień",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "daca31fd-cb87-4190-b484-108ecde4a889",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarchia dat",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Rok",
                "column": "Rok",
                "lineageTag": "e068e9aa-abb2-4d01-bc02-6d4dcd47155e",
                "ordinal": 0
              },
              {
                "name": "Kwartał",
                "column": "Kwartał",
                "lineageTag": "59edf727-8bf6-411b-9045-efbed8992335",
                "ordinal": 1
              },
              {
                "name": "Miesiąc",
                "column": "Miesiąc",
                "lineageTag": "25370b12-3238-40a1-9ba3-081b6e2b5f3f",
                "ordinal": 2
              },
              {
                "name": "Dzień",
                "column": "Dzień",
                "lineageTag": "5123ec7d-f0d2-4dbd-b6e8-50b3039a7959",
                "ordinal": 3
              }
            ],
            "lineageTag": "9b4d1bda-709e-4a0c-af86-358c48b151c5"
          }
        ],
        "isHidden": true,
        "lineageTag": "fbfe6d63-3b6d-4d7f-bdb1-d3980082d41c",
        "partitions": [
          {
            "name": "LocalDateTable_a6365485-89b3-443e-813a-358c7256be62",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Dim.City'[Valid To])), 1, 1), Date(Year(MAX('Dim.City'[Valid To])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Dim.Date",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Nawigacja"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "56ca1f79-deb5-4b50-ab17-ef3c79631237",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Odmiana",
                "defaultHierarchy": {
                  "hierarchy": "Hierarchia dat",
                  "table": "LocalDateTable_542427ae-981a-401c-8a73-c3f4814d107d"
                },
                "isDefault": true,
                "relationship": "8f7fdb9c-997e-4777-b722-ef9cecdfee74"
              }
            ]
          },
          {
            "name": "Day Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5b812116-2f12-4680-bf4d-63664d83adfb",
            "sourceColumn": "Day Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b02966c1-63c8-4539-be96-50fd511742a3",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Short Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe81ee61-1eec-4dbd-82c7-73ae62a53d82",
            "sourceColumn": "Short Month",
            "summarizeBy": "none"
          },
          {
            "name": "Calendar Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "474dc7c0-a501-4345-b3af-aa9fd08d9929",
            "sourceColumn": "Calendar Month Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Calendar Month Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "16c8374a-b888-4e78-97c9-2eac46819e3a",
            "sourceColumn": "Calendar Month Label",
            "summarizeBy": "none"
          },
          {
            "name": "Calendar Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "03eb2804-ce0e-4acc-8f07-c9eaed33415e",
            "sourceColumn": "Calendar Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Calendar Year Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2df3a6b9-5c62-4a91-9480-6da8bf723124",
            "sourceColumn": "Calendar Year Label",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0ab6251c-3eec-4811-ba52-b654ac6c48e2",
            "sourceColumn": "Fiscal Month Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Month Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "713b7a4e-b0c0-4c90-b5ba-dee4fe7c5828",
            "sourceColumn": "Fiscal Month Label",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3e1f665d-4e3e-44ec-9289-01bd9b4d13e6",
            "sourceColumn": "Fiscal Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Year Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "843a6a5c-8d73-47de-839e-904546239351",
            "sourceColumn": "Fiscal Year Label",
            "summarizeBy": "none"
          },
          {
            "name": "ISO Week Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "35cdfeb0-1b72-4a30-aaab-446ef8f1070d",
            "sourceColumn": "ISO Week Number",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "77045843-22a4-4212-ba93-b75cd00055e7",
        "partitions": [
          {
            "name": "Dim.Date",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = Sql.Databases(\"DESKTOP-FUKU640\\SQLEXPRESS\"),",
                "    WideWorldImportersDW = Źródło{[Name=\"WideWorldImportersDW\"]}[Data],",
                "    Dimension_Date = WideWorldImportersDW{[Schema=\"Dimension\",Item=\"Date\"]}[Data],",
                "    #\"Usunięto kolumny\" = Table.RemoveColumns(Dimension_Date,{\"Day\"})",
                "in",
                "    #\"Usunięto kolumny\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_542427ae-981a-401c-8a73-c3f4814d107d",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "32001531-242d-43e7-bf15-d10ef58fb441",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Rok",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7a6c32d7-35a1-4b46-8cc6-f058229ee3e9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Numer miesiąca",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "59c6f88f-ce57-4cc7-af7c-17861208e34c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Miesiąc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "f658785c-be34-4b6c-b5d7-34fb329b1882",
            "sortByColumn": "Numer miesiąca",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Numer kwartału",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([Numer miesiąca] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "afea6722-9e50-489e-9214-0094b759f270",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Kwartał",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [Numer kwartału]",
            "isHidden": true,
            "lineageTag": "1444e2cf-c015-45f6-b5cb-e6d6829c2ee0",
            "sortByColumn": "Numer kwartału",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dzień",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0ccd6611-8ff9-4382-bf48-cd7d68dbe371",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarchia dat",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Rok",
                "column": "Rok",
                "lineageTag": "52f97ac0-8dbb-42aa-a60b-202dab17e63a",
                "ordinal": 0
              },
              {
                "name": "Kwartał",
                "column": "Kwartał",
                "lineageTag": "a225ea20-a51c-4443-a0e3-0164957782cc",
                "ordinal": 1
              },
              {
                "name": "Miesiąc",
                "column": "Miesiąc",
                "lineageTag": "9d39fe60-6210-4294-ab7f-c8e70c26e6e4",
                "ordinal": 2
              },
              {
                "name": "Dzień",
                "column": "Dzień",
                "lineageTag": "8f5a8a91-d4c5-43e0-9220-679241599a9c",
                "ordinal": 3
              }
            ],
            "lineageTag": "b7737c0c-f1a4-495f-a086-ff1ae13c3796"
          }
        ],
        "isHidden": true,
        "lineageTag": "76ee6747-1ee2-41c7-b3bf-11bb8f23faff",
        "partitions": [
          {
            "name": "LocalDateTable_542427ae-981a-401c-8a73-c3f4814d107d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Dim.Date'[Date])), 1, 1), Date(Year(MAX('Dim.Date'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Dim.Stock_Item",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Nawigacja"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Stock Item Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a80a0148-16b4-40cb-b7c3-eba090959c1f",
            "sourceColumn": "Stock Item Key",
            "summarizeBy": "none"
          },
          {
            "name": "WWI Stock Item ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6502e7ba-f426-4538-bf5e-c6f7fdbd4715",
            "sourceColumn": "WWI Stock Item ID",
            "summarizeBy": "none"
          },
          {
            "name": "Stock Item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02b4ccd8-a63f-48b3-9555-539699c34d00",
            "sourceColumn": "Stock Item",
            "summarizeBy": "none"
          },
          {
            "name": "Color",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17aa788e-edb6-4887-984a-0dda4b8cb018",
            "sourceColumn": "Color",
            "summarizeBy": "none"
          },
          {
            "name": "Selling Package",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "357cda9e-c73e-40a3-8d4f-44b8581e76ec",
            "sourceColumn": "Selling Package",
            "summarizeBy": "none"
          },
          {
            "name": "Buying Package",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3ed144ca-c92d-4f7c-a2e4-4a21577e38a0",
            "sourceColumn": "Buying Package",
            "summarizeBy": "none"
          },
          {
            "name": "Brand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af01c16f-f8e6-48ee-b420-fdde6f3c5b2c",
            "sourceColumn": "Brand",
            "summarizeBy": "none"
          },
          {
            "name": "Size",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5242af70-3228-493a-a0d5-1760668fdb74",
            "sourceColumn": "Size",
            "summarizeBy": "none"
          },
          {
            "name": "Lead Time Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c5f0b7af-085a-4350-9a11-055ab309c53f",
            "sourceColumn": "Lead Time Days",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantity Per Outer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dc9f0843-5058-4351-8521-58daa499990b",
            "sourceColumn": "Quantity Per Outer",
            "summarizeBy": "sum"
          },
          {
            "name": "Is Chiller Stock",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "64fa2ff3-ce0e-4b36-a695-9fd051bee853",
            "sourceColumn": "Is Chiller Stock",
            "summarizeBy": "none"
          },
          {
            "name": "Barcode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c8422d4b-20d7-4509-a710-12399f959b21",
            "sourceColumn": "Barcode",
            "summarizeBy": "none"
          },
          {
            "name": "Tax Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "648f013b-42ad-4afd-a7b0-26b3813488c0",
            "sourceColumn": "Tax Rate",
            "summarizeBy": "sum"
          },
          {
            "name": "Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3c68cb7b-3ca2-4874-a3ac-8e1347d946ef",
            "sourceColumn": "Unit Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Recommended Retail Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "40ada1af-f128-4c35-b186-d7d2ad282291",
            "sourceColumn": "Recommended Retail Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Typical Weight Per Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "77506667-fe30-46cd-a7a6-8c9c431c3b14",
            "sourceColumn": "Typical Weight Per Unit",
            "summarizeBy": "sum"
          },
          {
            "name": "Valid From",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "8a57ffd0-7961-47e9-8bbc-9c4b2b8f6778",
            "sourceColumn": "Valid From",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Odmiana",
                "defaultHierarchy": {
                  "hierarchy": "Hierarchia dat",
                  "table": "LocalDateTable_43c04760-7e1c-4782-bd68-e56b14dcf4bb"
                },
                "isDefault": true,
                "relationship": "b1fe0bdb-c1ff-43cb-a5d7-738d6ac8675f"
              }
            ]
          },
          {
            "name": "Valid To",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "e3e58114-155c-4914-bff3-996f2f1887aa",
            "sourceColumn": "Valid To",
            "summarizeBy": "none"
          },
          {
            "name": "Lineage Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "249ab214-eef5-403c-921a-f3ef4ac855a1",
            "sourceColumn": "Lineage Key",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "cd07a76e-11a6-4a92-8b4a-f9502fbf9a56",
        "partitions": [
          {
            "name": "Dim.Stock_Item",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = Sql.Databases(\"DESKTOP-FUKU640\\SQLEXPRESS\"),",
                "    WideWorldImportersDW = Źródło{[Name=\"WideWorldImportersDW\"]}[Data],",
                "    #\"Dimension_Stock Item\" = WideWorldImportersDW{[Schema=\"Dimension\",Item=\"Stock Item\"]}[Data],",
                "    #\"Usunięto pierwsze wiersze\" = Table.Skip(#\"Dimension_Stock Item\",1),",
                "    #\"Usunięto kolumny\" = Table.RemoveColumns(#\"Usunięto pierwsze wiersze\",{\"Photo\"})",
                "in",
                "    #\"Usunięto kolumny\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_43c04760-7e1c-4782-bd68-e56b14dcf4bb",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "18bd7ac3-6aed-4290-980f-aa5b6842ca40",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Rok",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9e577be7-b356-4e1c-945e-4950fe05da3c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Numer miesiąca",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c48f43b1-e67a-4a88-a728-3f6344192004",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Miesiąc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "8375e5d6-d2b3-4e5e-8383-407d63df8601",
            "sortByColumn": "Numer miesiąca",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Numer kwartału",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([Numer miesiąca] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c7f79ca9-afca-4b93-b5ec-ecff564c3b33",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Kwartał",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [Numer kwartału]",
            "isHidden": true,
            "lineageTag": "55b9b231-388c-46b2-b580-9f4101536a87",
            "sortByColumn": "Numer kwartału",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dzień",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "643b3012-4d0c-4fb5-8191-6983c75967ca",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarchia dat",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Rok",
                "column": "Rok",
                "lineageTag": "47106bab-9b12-4363-a836-90ad939b255c",
                "ordinal": 0
              },
              {
                "name": "Kwartał",
                "column": "Kwartał",
                "lineageTag": "c4016aa0-6a78-4274-8079-8794d09167c7",
                "ordinal": 1
              },
              {
                "name": "Miesiąc",
                "column": "Miesiąc",
                "lineageTag": "228d6ee0-253f-4319-bdd8-12bd60b051e3",
                "ordinal": 2
              },
              {
                "name": "Dzień",
                "column": "Dzień",
                "lineageTag": "837269b4-ed39-4427-a96e-2e5f5bde54b5",
                "ordinal": 3
              }
            ],
            "lineageTag": "080979d3-8d3f-4a74-9e32-3c74d8c822b2"
          }
        ],
        "isHidden": true,
        "lineageTag": "4f1e6176-e59e-431d-bb18-2dc90e4464e4",
        "partitions": [
          {
            "name": "LocalDateTable_43c04760-7e1c-4782-bd68-e56b14dcf4bb",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Dim.Stock_Item'[Valid From])), 1, 1), Date(Year(MAX('Dim.Stock_Item'[Valid From])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Fact.Stock_Holding",
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "Stock Holding Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "78be0302-aacd-4102-81ed-6558755df9dd",
            "sourceColumn": "Stock Holding Key",
            "summarizeBy": "count"
          },
          {
            "name": "Stock Item Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6b272b99-7419-4708-b983-d0f124d34810",
            "sourceColumn": "Stock Item Key",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity On Hand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "892def60-1a48-4cf6-a9e3-6a0c272cc8cf",
            "sourceColumn": "Quantity On Hand",
            "summarizeBy": "sum"
          },
          {
            "name": "Bin Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50039e14-c8fd-43a9-b7d1-6a0a14af9f92",
            "sourceColumn": "Bin Location",
            "summarizeBy": "none"
          },
          {
            "name": "Last Stocktake Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "404b2396-55bd-4dbf-96e1-9150e49169c5",
            "sourceColumn": "Last Stocktake Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Last Cost Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1da762fd-b58b-42aa-aaa7-fae43472b853",
            "sourceColumn": "Last Cost Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Reorder Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3913bf4e-afa3-4aa8-adb1-168d71c93ac3",
            "sourceColumn": "Reorder Level",
            "summarizeBy": "sum"
          },
          {
            "name": "Target Stock Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b497d679-6f12-454d-ae8d-35f106d716ab",
            "sourceColumn": "Target Stock Level",
            "summarizeBy": "sum"
          },
          {
            "name": "Lineage Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9431f9c1-ee60-4c05-8715-48cac2f00dbf",
            "sourceColumn": "Lineage Key",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "7fab8090-6716-4b20-8854-c27324e9a84c",
        "partitions": [
          {
            "name": "Fact.Stock_Holding",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = Sql.Databases(\"DESKTOP-FUKU640\\SQLEXPRESS\"),",
                "    WideWorldImportersDW = Źródło{[Name=\"WideWorldImportersDW\"]}[Data],",
                "    #\"Fact_Stock Holding\" = WideWorldImportersDW{[Schema=\"Fact\",Item=\"Stock Holding\"]}[Data]",
                "in",
                "    #\"Fact_Stock Holding\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim.Supplier",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Nawigacja"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Supplier Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "23b64b78-9e4a-494e-ad83-cd9003772b2f",
            "sourceColumn": "Supplier Key",
            "summarizeBy": "count"
          },
          {
            "name": "WWI Supplier ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "99cd29cf-5e95-46a7-a2c2-d672529fce25",
            "sourceColumn": "WWI Supplier ID",
            "summarizeBy": "count"
          },
          {
            "name": "Supplier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db1ec18e-478a-48f5-aa8b-6b20273246ba",
            "sourceColumn": "Supplier",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f62cb309-38ce-4c21-bfb0-ed8564d251ac",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Primary Contact",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "25c1ab18-712a-44b5-84ca-247d7c66a6bf",
            "sourceColumn": "Primary Contact",
            "summarizeBy": "none"
          },
          {
            "name": "Supplier Reference",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8adf6c0f-ea1b-41f9-ab3c-0a3127b3e756",
            "sourceColumn": "Supplier Reference",
            "summarizeBy": "none"
          },
          {
            "name": "Payment Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8d9d6b7c-298a-4e92-9113-fbff26a12eb0",
            "sourceColumn": "Payment Days",
            "summarizeBy": "sum"
          },
          {
            "name": "Postal Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "779049d3-d6cd-4750-8f74-b5adb8e093b0",
            "sourceColumn": "Postal Code",
            "summarizeBy": "none"
          },
          {
            "name": "Valid From",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "f0373cb9-beed-4c87-9bec-f0d6755c678e",
            "sourceColumn": "Valid From",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Odmiana",
                "defaultHierarchy": {
                  "hierarchy": "Hierarchia dat",
                  "table": "LocalDateTable_da1d75ef-d80e-4d3a-9e90-1f338481d234"
                },
                "isDefault": true,
                "relationship": "9904e94f-a718-4cc0-ab48-06121bf25ccf"
              }
            ]
          },
          {
            "name": "Valid To",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "426bec07-724c-44d0-846f-5d469cd34f5a",
            "sourceColumn": "Valid To",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Odmiana",
                "defaultHierarchy": {
                  "hierarchy": "Hierarchia dat",
                  "table": "LocalDateTable_d432e486-5164-49fe-9113-448518a0a78a"
                },
                "isDefault": true,
                "relationship": "9259438b-8832-4ae9-a7c8-9a901b9b37a9"
              }
            ]
          },
          {
            "name": "Lineage Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6e5fa631-555c-47c5-b8e8-fb2c0d31a391",
            "sourceColumn": "Lineage Key",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "35bd9b7b-d008-453c-85d0-0292ff323a96",
        "partitions": [
          {
            "name": "Dim.Supplier",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = Sql.Databases(\"DESKTOP-FUKU640\\SQLEXPRESS\"),",
                "    WideWorldImportersDW = Źródło{[Name=\"WideWorldImportersDW\"]}[Data],",
                "    Dimension_Supplier = WideWorldImportersDW{[Schema=\"Dimension\",Item=\"Supplier\"]}[Data],",
                "    #\"Usunięto pierwsze wiersze\" = Table.Skip(Dimension_Supplier,1)",
                "in",
                "    #\"Usunięto pierwsze wiersze\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_da1d75ef-d80e-4d3a-9e90-1f338481d234",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2d02fb76-db79-4f26-8763-88467597a23d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Rok",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0635d780-996b-4bb2-b561-a87f4d372dae",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Numer miesiąca",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "61cfdf60-6158-4735-8800-dc2379b0d82c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Miesiąc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "47e993a4-a0ad-4271-98a6-839f1eeb6815",
            "sortByColumn": "Numer miesiąca",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Numer kwartału",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([Numer miesiąca] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5e3abf6b-90de-4e12-8f8d-d30c4a7968e0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Kwartał",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [Numer kwartału]",
            "isHidden": true,
            "lineageTag": "0d27f73b-eaff-44d5-a9a7-326c6d06658b",
            "sortByColumn": "Numer kwartału",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dzień",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e69ec783-e0e4-413c-b8af-eb49a1c5d83a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarchia dat",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Rok",
                "column": "Rok",
                "lineageTag": "ea9f7f61-b9f5-4e6d-ab20-383475de687d",
                "ordinal": 0
              },
              {
                "name": "Kwartał",
                "column": "Kwartał",
                "lineageTag": "a351296d-f40b-4111-ad15-6ad23ae754a7",
                "ordinal": 1
              },
              {
                "name": "Miesiąc",
                "column": "Miesiąc",
                "lineageTag": "8cd3cf55-6cda-459a-8d9c-32e8b056084b",
                "ordinal": 2
              },
              {
                "name": "Dzień",
                "column": "Dzień",
                "lineageTag": "1b9f045f-011d-46b9-a1a4-e74a04d7dc58",
                "ordinal": 3
              }
            ],
            "lineageTag": "ac428e96-787f-42d5-b726-62956d686cd5"
          }
        ],
        "isHidden": true,
        "lineageTag": "e1ff853c-8998-4f8c-8b20-5caa3f6a18b2",
        "partitions": [
          {
            "name": "LocalDateTable_da1d75ef-d80e-4d3a-9e90-1f338481d234",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Dim.Supplier'[Valid From])), 1, 1), Date(Year(MAX('Dim.Supplier'[Valid From])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_d432e486-5164-49fe-9113-448518a0a78a",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7a864331-56f7-4601-a64d-499c4025f383",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Rok",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "39f0b05a-229e-4b25-b6a8-f068d098f1da",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Numer miesiąca",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0b732f50-eea0-4853-976a-40195232f42e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Miesiąc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ec2aca85-12fc-4b6f-97d7-35eac9c7897a",
            "sortByColumn": "Numer miesiąca",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Numer kwartału",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([Numer miesiąca] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "04133e70-8690-4bbb-9d07-6cc392533bde",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Kwartał",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [Numer kwartału]",
            "isHidden": true,
            "lineageTag": "07c8675b-8140-4dfe-9e68-56b0563433f3",
            "sortByColumn": "Numer kwartału",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dzień",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ed7be422-7955-463c-8a64-69dd0e6f1f1a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarchia dat",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Rok",
                "column": "Rok",
                "lineageTag": "4cbe0763-b2f6-4d74-9365-bbf423634594",
                "ordinal": 0
              },
              {
                "name": "Kwartał",
                "column": "Kwartał",
                "lineageTag": "1eac99cf-de4a-4a07-8435-1ef1f167576b",
                "ordinal": 1
              },
              {
                "name": "Miesiąc",
                "column": "Miesiąc",
                "lineageTag": "5a82c947-d890-4b76-9363-a13889f39389",
                "ordinal": 2
              },
              {
                "name": "Dzień",
                "column": "Dzień",
                "lineageTag": "f75d6130-94ef-49b0-ac31-99cd37f9d44f",
                "ordinal": 3
              }
            ],
            "lineageTag": "f6a985b4-4b9b-4b24-9e8e-197ea2c5daa8"
          }
        ],
        "isHidden": true,
        "lineageTag": "45aefbf1-0bc6-4b54-8518-af65c7f74cc3",
        "partitions": [
          {
            "name": "LocalDateTable_d432e486-5164-49fe-9113-448518a0a78a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Dim.Supplier'[Valid To])), 1, 1), Date(Year(MAX('Dim.Supplier'[Valid To])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Dim.Category",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "WWI Stock Item ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c7dc00ee-a736-4b65-8c85-a643d98ed13d",
            "sourceColumn": "WWI Stock Item ID",
            "summarizeBy": "none"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3f29565-e8aa-464f-ad52-b86d24b8f574",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "000caa38-dd04-40dc-82fd-746456cca9e8",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0222ad08-785b-4c2c-98f0-28c782309f8c",
        "partitions": [
          {
            "name": "Dim.Category",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = Excel.Workbook(File.Contents(\"C:\\Users\\baadi\\OneDrive - Politechnika Łódzka\\st2\\sem3\\BI\\Lab - dane-20241009\\Dodatkowe dane\\Category_dictionary.xlsx\"), null, true),",
                "    Arkusz1_Sheet = Źródło{[Item=\"Arkusz1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Nagłówki o podwyższonym poziomie\" = Table.PromoteHeaders(Arkusz1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Zmieniono typ\" = Table.TransformColumnTypes(#\"Nagłówki o podwyższonym poziomie\",{{\"WWI Stock Item ID\", Int64.Type}, {\"Description\", type text}, {\"Category\", type text}})",
                "in",
                "    #\"Zmieniono typ\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim.Color",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Nawigacja"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Color",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7161c515-839c-425b-85a1-a766380acb66",
            "sourceColumn": "Color",
            "summarizeBy": "none"
          },
          {
            "name": "Background Color Format",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b82f515-e85f-433f-834d-022980212321",
            "sourceColumn": "Background Color Format",
            "summarizeBy": "none"
          },
          {
            "name": "Font Color Format",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2202482c-de88-4e1f-a07c-114af3721f38",
            "sourceColumn": "Font Color Format",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6e3a0b8e-d887-4152-9d20-f1cead529cd6",
        "partitions": [
          {
            "name": "Dim.Color",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Źródło = Csv.Document(File.Contents(\"C:\\Users\\baadi\\OneDrive - Politechnika Łódzka\\st2\\sem3\\BI\\Lab - dane-20241009\\Dodatkowe dane\\Color Formats.csv\"),[Delimiter=\";\", Columns=3, Encoding=1250, QuoteStyle=QuoteStyle.None]),",
                "    #\"Zmieniono typ\" = Table.TransformColumnTypes(Źródło,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}}),",
                "    #\"Nagłówki o podwyższonym poziomie\" = Table.PromoteHeaders(#\"Zmieniono typ\", [PromoteAllScalars=true]),",
                "    #\"Zmieniono typ1\" = Table.TransformColumnTypes(#\"Nagłówki o podwyższonym poziomie\",{{\"Color\", type text}, {\"Background Color Format\", type text}, {\"Font Color Format\", type text}})",
                "in",
                "    #\"Zmieniono typ1\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}