{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"DimCity\",\"DimCustomer\",\"DimDate\",\"DimSalesperson\",\"DimProduct\",\"FactSale\",\"DimTarget\",\"Color Formats\",\"Employee_csv\",\"DimCategory\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.137.1102.0 (24.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "fastCombine": true,
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Color Formats",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\janek\\OneDrive\\Pulpit\\PowerBI\\Lab - dane-20241009\\Dodatkowe dane\\Color Formats.csv\"),[Delimiter=\";\", Columns=3, Encoding=1250, QuoteStyle=QuoteStyle.None]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}}),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Color\", type text}, {\"Background Color Format\", type text}, {\"Font Color Format\", type text}})",
          "in",
          "    #\"Changed Type1\""
        ],
        "kind": "m",
        "lineageTag": "5408731d-68df-45c2-817c-7330d4231312"
      }
    ],
    "relationships": [
      {
        "name": "5559d8a2-9537-48a0-9a79-fd2a244877c1",
        "fromColumn": "Valid From",
        "fromTable": "DimCity",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_1ccf020c-a33d-4b1c-bf7f-f703654af62f"
      },
      {
        "name": "190c43d6-0c64-488c-8a6a-99fc72db9eec",
        "fromColumn": "Valid To",
        "fromTable": "DimCity",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_43616315-e001-4d34-b76b-c3c74b570f78"
      },
      {
        "name": "3c2674dd-bd69-42ff-a58e-81b47f0f0048",
        "fromColumn": "Valid From",
        "fromTable": "DimCustomer",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_54fd3187-df43-4063-86ce-1603579c3762"
      },
      {
        "name": "7d2b95e8-f305-46f3-9ac7-5d5505a1f9dd",
        "fromColumn": "Valid To",
        "fromTable": "DimCustomer",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_daf29924-c8cc-4c6d-b7b0-b92af7fa936f"
      },
      {
        "name": "b290de8a-947f-4bf9-9384-e371c92cb478",
        "fromColumn": "Valid From",
        "fromTable": "DimSalesperson",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_32b131e5-4c2b-49d3-ba8f-7c933e2a392b"
      },
      {
        "name": "76c1524e-de7a-47d0-8baf-c1ab0921f469",
        "fromColumn": "Valid To",
        "fromTable": "DimSalesperson",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_d5321435-4ae4-4c92-9cac-e8572d377201"
      },
      {
        "name": "3ff2e7d9-7634-4b6a-938a-e92be52cd98a",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "City Key",
        "fromTable": "FactSale",
        "toColumn": "City Key",
        "toTable": "DimCity"
      },
      {
        "name": "06407745-69a5-44a1-bcbe-4809b18ca24a",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "Customer Key",
        "fromTable": "FactSale",
        "isActive": false,
        "toColumn": "Customer Key",
        "toTable": "DimCustomer"
      },
      {
        "name": "81ff0847-e7f4-4cbd-b1d5-eacf241cc714",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "Delivery Date",
        "fromTable": "FactSale",
        "toColumn": "Date",
        "toTable": "DimDate"
      },
      {
        "name": "1adc4de4-94f4-4e5f-8812-2da1d176ce49",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "Invoice Date",
        "fromTable": "FactSale",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "DimDate"
      },
      {
        "name": "eede9980-b8ba-4285-a865-63ed1e5c6f3b",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "Salesperson Key",
        "fromTable": "FactSale",
        "toColumn": "EmployeeId",
        "toTable": "DimSalesperson"
      },
      {
        "name": "81e1ea45-472f-593c-4da0-1ad9e644b9b1",
        "fromColumn": "Stock Item Key",
        "fromTable": "FactSale",
        "toColumn": "Stock Item Key",
        "toTable": "DimProduct"
      },
      {
        "name": "4cd6e21e-0887-4c2e-86e0-2021c5775ba0",
        "fromColumn": "Date",
        "fromTable": "Dates_1",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2e833427-8579-4df0-8f16-4a674172c644"
      },
      {
        "name": "3ae5f9de-fc04-fa18-b7d5-4dfa1e97259b",
        "fromColumn": "TargetMonth",
        "fromTable": "DimTarget",
        "toColumn": "Date",
        "toTable": "DimDate"
      },
      {
        "name": "cbb1b8e0-cc3f-d4a5-6fa6-71ea60339fe4",
        "fromColumn": "EmployeeID",
        "fromTable": "DimTarget",
        "toColumn": "EmployeeId",
        "toTable": "DimSalesperson"
      }
    ],
    "roles": [
      {
        "name": "OH",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "3e83a5a596434edcaadf5f753c3d026c"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "DimProduct",
            "filterExpression": "[Category] == \"Office & Humor\""
          }
        ]
      },
      {
        "name": "Email",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c551f7c7ebe543e3a01c55a488e9f3e2"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "DimSalesperson",
            "filterExpression": "[EmailAddress] == USERPRINCIPALNAME()"
          },
          {
            "name": "_Measures"
          }
        ]
      }
    ],
    "sourceQueryCulture": "pl-PL",
    "tables": [
      {
        "name": "DimCity",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "City Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "23521315-82b7-41f5-9461-f615fe568aa4",
            "sourceColumn": "City Key",
            "summarizeBy": "none"
          },
          {
            "name": "WWI City ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f559a9a1-f731-41cb-ab5a-d45977348850",
            "sourceColumn": "WWI City ID",
            "summarizeBy": "count"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "City",
            "dataType": "string",
            "lineageTag": "84299d36-b3f8-412a-bc3b-a43d74dc41bb",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "State Province",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "StateOrProvince",
            "dataType": "string",
            "lineageTag": "e9de65b6-8611-4b96-bc89-9c6aec0dc68d",
            "sourceColumn": "State Province",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Country",
            "dataType": "string",
            "lineageTag": "540d08af-4bb3-4952-938b-5d42a9328009",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Continent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Continent",
            "dataType": "string",
            "lineageTag": "57cdf785-ebce-4058-b548-5d9c0bb58dfa",
            "sourceColumn": "Continent",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Territory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c74470e8-4fc1-4c5b-abff-ba653301ede1",
            "sourceColumn": "Sales Territory",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc69247d-ff0e-4082-816e-81a08b1a2549",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Subregion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d162de8f-766a-4d77-8d78-2dfd1a59dc1e",
            "sourceColumn": "Subregion",
            "summarizeBy": "none"
          },
          {
            "name": "Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af316c01-0d0f-4697-94bd-8f1ee6d7f6e3",
            "sourceColumn": "Location",
            "summarizeBy": "none"
          },
          {
            "name": "Latest Recorded Population",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3944e566-49ba-4f9b-bbd8-6a454d27a5b8",
            "sourceColumn": "Latest Recorded Population",
            "summarizeBy": "sum"
          },
          {
            "name": "Valid From",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "931cb0f8-2f2e-4f5f-81c8-f3ff5582925e",
            "sourceColumn": "Valid From",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_1ccf020c-a33d-4b1c-bf7f-f703654af62f"
                },
                "isDefault": true,
                "relationship": "5559d8a2-9537-48a0-9a79-fd2a244877c1"
              }
            ]
          },
          {
            "name": "Valid To",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "5801c007-9582-437f-9010-d2deaceca33c",
            "sourceColumn": "Valid To",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_43616315-e001-4d34-b76b-c3c74b570f78"
                },
                "isDefault": true,
                "relationship": "190c43d6-0c64-488c-8a6a-99fc72db9eec"
              }
            ]
          }
        ],
        "hierarchies": [
          {
            "name": "Region Hierarchy",
            "levels": [
              {
                "name": "Region",
                "column": "Region",
                "lineageTag": "6bc421b6-05b9-411d-a8ee-0da99a09db7c",
                "ordinal": 0
              },
              {
                "name": "Subregion",
                "column": "Subregion",
                "lineageTag": "d7ea1d60-9d45-4c2b-a7e9-16c1f41402d8",
                "ordinal": 1
              },
              {
                "name": "Continent",
                "column": "Continent",
                "lineageTag": "9c2a5ef6-5d00-48df-a137-ba5fbde997c4",
                "ordinal": 2
              },
              {
                "name": "Country",
                "column": "Country",
                "lineageTag": "a67ee407-dae8-4126-bea9-be03b0d52fdb",
                "ordinal": 3
              },
              {
                "name": "State Province",
                "column": "State Province",
                "lineageTag": "b1ea2849-f5c6-4656-9925-94adc3e02906",
                "ordinal": 4
              },
              {
                "name": "City",
                "column": "City",
                "lineageTag": "d41b836d-eb0e-46a4-8861-8bebdaba0818",
                "ordinal": 5
              }
            ],
            "lineageTag": "ce926525-4b4f-4c54-9bec-ae6643f514e3"
          }
        ],
        "lineageTag": "fc0cd4e6-43d0-4b1a-863d-9eca0fa839d1",
        "partitions": [
          {
            "name": "DimCity",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\", \"WideWorldImportersDW\"),",
                "    Dimension_City = Source{[Schema=\"Dimension\",Item=\"City\"]}[Data],",
                "    #\"Removed Top Rows\" = Table.Skip(Dimension_City,1),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Removed Top Rows\",{\"Lineage Key\", \"Fact.Order\", \"Fact.Sale\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_49afc99e-9a5f-49a3-96c1-042bd105b64c",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b9a507b1-ba30-4163-9861-1ec77031a582",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "3d4011c1-a372-47b4-a596-232db9271be9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "7dffa8d2-0875-47c1-a42b-dda69c9c1718",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "f7673027-258b-4a90-91fe-fc0b53a8ba4a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "47fca0a2-8c30-4d63-ad2f-6cfc30f469f4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "72fbc9dd-b8a0-4234-95bd-8186650baf74",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "bab2b96a-2293-41d7-a73c-b45896e2fd04",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "e14f8cbb-cf99-4443-9bb4-ab33425bd039",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "fec46925-39d2-4520-b5a3-e229a68cd51b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5a2ddcfb-7239-4754-b355-857ccc6d7ed1",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "0daebaf1-efb4-4fe4-a235-7f58f8eff233",
                "ordinal": 3
              }
            ],
            "lineageTag": "2b0bf6c1-80ed-4951-8715-305c5aefa386"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "eb6b2112-95c8-45e8-bb44-e6e0a2916177",
        "partitions": [
          {
            "name": "DateTableTemplate_49afc99e-9a5f-49a3-96c1-042bd105b64c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_1ccf020c-a33d-4b1c-bf7f-f703654af62f",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9d753203-fcd3-4b70-9d78-54757abac0f5",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "55ff8aeb-62c2-4a90-af18-95fcc4b2a598",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "874c982f-82d4-48ba-9c50-50bde364dd33",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "502c33e0-119f-4383-81e9-147b1e045ebf",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "07727cf9-e696-4277-b41d-04cdf26c37a8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "74c86fd4-54ee-4ea0-96e7-8206a2473f80",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "b4a60a9c-8224-4bc1-9682-cce8913fb70d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f1274f37-6052-4d18-ab17-4c10157882fe",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "e78e62fe-2954-4244-ab74-9713354504da",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "c669d79c-55ff-4eca-a8c5-bff9a1c0fc06",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "17210155-70b6-4349-b712-0343b44a3e0c",
                "ordinal": 3
              }
            ],
            "lineageTag": "286ed60d-6730-4cae-b37f-8abce2913f5e"
          }
        ],
        "isHidden": true,
        "lineageTag": "0f023c24-1d5c-49bb-9cc6-ba7a62e5f9e2",
        "partitions": [
          {
            "name": "LocalDateTable_1ccf020c-a33d-4b1c-bf7f-f703654af62f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DimCity'[Valid From])), 1, 1), Date(Year(MAX('DimCity'[Valid From])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_43616315-e001-4d34-b76b-c3c74b570f78",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c8d19abb-d0ac-4cb6-964c-38c3491fc64e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "83c23352-4eef-4802-8c09-f313f9d0ce95",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "b8848d16-4ea7-4f1e-993a-585ded30fb00",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "7dc47040-bfcc-42ee-914d-f41ea8491e36",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "97d49c75-114b-4977-82dc-adbde32fafc4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "4a62e434-4886-44e9-9b69-1e2cec30073d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "3fd3ca6f-2e89-4077-9651-e1a83dbb48e7",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "056ff19d-19f6-498b-ac8b-5b3911e60458",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "1118dddb-822c-4fb4-b465-dce3d28a7402",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "9fc6b7da-41f1-4baa-9054-3881ca90bfe1",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "4ac444a3-0851-4032-8d5c-11f9a5ac78eb",
                "ordinal": 3
              }
            ],
            "lineageTag": "be6e2fea-6af9-49f4-a0d5-e1fe3758b165"
          }
        ],
        "isHidden": true,
        "lineageTag": "251bd247-3404-4304-ae19-ba4352bbd215",
        "partitions": [
          {
            "name": "LocalDateTable_43616315-e001-4d34-b76b-c3c74b570f78",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DimCity'[Valid To])), 1, 1), Date(Year(MAX('DimCity'[Valid To])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "DimCustomer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Customer Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c5ceb0bc-508f-4d02-8af3-b9a838ea06bd",
            "sourceColumn": "Customer Key",
            "summarizeBy": "count"
          },
          {
            "name": "WWI Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a02dd64b-9881-475e-99d6-9ff64bbfc67d",
            "sourceColumn": "WWI Customer ID",
            "summarizeBy": "count"
          },
          {
            "name": "Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2bd90845-9ef0-4dd1-8ea4-ef2872e33551",
            "sourceColumn": "Customer",
            "summarizeBy": "none"
          },
          {
            "name": "Bill To Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "12e3dadc-a71e-47d6-bc3a-2cbe53c4dd26",
            "sourceColumn": "Bill To Customer",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "49d420c4-4232-4fb4-a84c-831f20b3c234",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Buying Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb5fb710-3521-4db3-b8ca-641ac8b16f47",
            "sourceColumn": "Buying Group",
            "summarizeBy": "none"
          },
          {
            "name": "Primary Contact",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed3a10d7-1161-44a5-90d7-3e6d8ab394b9",
            "sourceColumn": "Primary Contact",
            "summarizeBy": "none"
          },
          {
            "name": "Postal Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "PostalCode",
            "dataType": "string",
            "lineageTag": "02012c98-edab-494f-a58c-a8e833bcbbb5",
            "sourceColumn": "Postal Code",
            "summarizeBy": "none"
          },
          {
            "name": "Valid From",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "9a16490b-ce49-4568-8249-c58de395b2b9",
            "sourceColumn": "Valid From",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_54fd3187-df43-4063-86ce-1603579c3762"
                },
                "isDefault": true,
                "relationship": "3c2674dd-bd69-42ff-a58e-81b47f0f0048"
              }
            ]
          },
          {
            "name": "Valid To",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "1f33f2a6-a0fc-4a05-a9a2-9c4f66ce5168",
            "sourceColumn": "Valid To",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_daf29924-c8cc-4c6d-b7b0-b92af7fa936f"
                },
                "isDefault": true,
                "relationship": "7d2b95e8-f305-46f3-9ac7-5d5505a1f9dd"
              }
            ]
          }
        ],
        "hierarchies": [
          {
            "name": "Customers",
            "levels": [
              {
                "name": "Buying Group",
                "column": "Buying Group",
                "lineageTag": "322646a2-8b43-4c26-b522-fd2323a5c8f5",
                "ordinal": 0
              },
              {
                "name": "Customer",
                "column": "Customer",
                "lineageTag": "318a67d7-9b63-4b22-83bf-87067cb3e91f",
                "ordinal": 1
              }
            ],
            "lineageTag": "5af3cb41-a885-4c24-8f8e-f4e2831138a3"
          }
        ],
        "lineageTag": "3fe40590-fbfc-409e-8beb-64dc6896dc65",
        "partitions": [
          {
            "name": "DimCustomer",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\", \"WideWorldImportersDW\"),",
                "    Dimension_Customer = Source{[Schema=\"Dimension\",Item=\"Customer\"]}[Data],",
                "    #\"Removed Top Rows\" = Table.Skip(Dimension_Customer,1),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Removed Top Rows\",{\"Lineage Key\", \"Fact.Movement\", \"Fact.Order\", \"Fact.Sale(Customer Key)\", \"Fact.Sale(Customer Key) 2\", \"Fact.Transaction(Customer Key)\", \"Fact.Transaction(Customer Key) 2\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_54fd3187-df43-4063-86ce-1603579c3762",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1867236e-0aca-4f1b-bc84-57f210be0495",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "04d9685a-5232-4fdc-8e0b-fdca78d826fc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "0eaebf5d-7d30-4a32-8ab1-a9164d367d29",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "406f2516-2940-4613-b915-3c604e3f324f",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "8d8f9278-589d-4513-a770-1fbbec321597",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "10403003-003c-446e-a782-a3b3f9eb5649",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "5585d0ca-0dff-4e90-a0c1-23f3967a26de",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "dfd6a186-5d1c-4827-85bb-2b53ccb62d14",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "aaa81661-0238-4e0c-9325-e14b82bb754f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "36d61757-16fc-4d44-be2a-674e8fc8a815",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "71c5db40-6c85-4cf5-84e7-05a95f30d109",
                "ordinal": 3
              }
            ],
            "lineageTag": "ec9108cf-40bc-4cf7-ac6c-eb3afae86f16"
          }
        ],
        "isHidden": true,
        "lineageTag": "464ea2e7-de69-4d4e-b661-d6c325424f6e",
        "partitions": [
          {
            "name": "LocalDateTable_54fd3187-df43-4063-86ce-1603579c3762",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DimCustomer'[Valid From])), 1, 1), Date(Year(MAX('DimCustomer'[Valid From])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_daf29924-c8cc-4c6d-b7b0-b92af7fa936f",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "907e5c1c-30a2-48a7-a523-918c3d673347",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "d456927f-a97a-4846-839c-8b77a580d5f6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "49e4c943-6c6a-4861-ad85-75fe6f308a91",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "06bebace-7cf8-4283-ba5a-d9411df38947",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "15f5b314-1453-4353-b205-996ca14fa536",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "007a27cc-0870-4a0d-9d77-5904983d03cf",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "c25de031-26eb-4538-bee1-26ae675d3c88",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "82fc14a1-d59a-41e7-91a1-f421a8bc57f8",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "3c214f99-2152-4f0c-affe-1180d1be5c85",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "59a88172-7b91-4ff3-a78b-ca96ff941f48",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "be0080de-2223-42be-986e-081ba931413a",
                "ordinal": 3
              }
            ],
            "lineageTag": "42cf0c9f-1c65-411b-abe9-0da68d6d1abd"
          }
        ],
        "isHidden": true,
        "lineageTag": "d3051b1d-3861-4ff0-bf5e-94df86efaafb",
        "partitions": [
          {
            "name": "LocalDateTable_daf29924-c8cc-4c6d-b7b0-b92af7fa936f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DimCustomer'[Valid To])), 1, 1), Date(Year(MAX('DimCustomer'[Valid To])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "DimDate",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isKey": true,
            "lineageTag": "66a35b35-dad9-416d-886e-0a9ad36a9542",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Day Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0f24d957-835e-453e-8206-34a0d7f05fae",
            "sourceColumn": "Day Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b942057b-e644-46e1-9fa5-919e4f888f74",
            "sourceColumn": "Day",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "c4411eaa-3c1a-4f59-8ce5-48b512d77d9c",
            "sortByColumn": "Calendar Month Number",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Short Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5de385ca-97d8-49f8-8f8c-5b646d736e4a",
            "sourceColumn": "Short Month",
            "summarizeBy": "none"
          },
          {
            "name": "Calendar Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e181ceac-84e0-4835-8a1e-8787ac30c60c",
            "sourceColumn": "Calendar Month Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Calendar Month Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82e73983-fa1c-4468-a226-0156d345df2f",
            "sourceColumn": "Calendar Month Label",
            "summarizeBy": "none"
          },
          {
            "name": "Calendar Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "845b42e3-8059-4654-ba8e-2b29a7ad98e3",
            "sourceColumn": "Calendar Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Calendar Year Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7535ee5e-260e-48a2-93bb-c71a78c4165e",
            "sourceColumn": "Calendar Year Label",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "79c20dc8-0c36-460a-9710-06a74cec91d8",
            "sourceColumn": "Fiscal Month Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Month Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ca60e9c5-ebdc-4d7d-8271-9d79dd4cf836",
            "sourceColumn": "Fiscal Month Label",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d3b41ba3-1721-43af-82b8-5b538f102fc5",
            "sourceColumn": "Fiscal Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Year Label",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac0058aa-ea76-4679-a49b-c563191d54d1",
            "sourceColumn": "Fiscal Year Label",
            "summarizeBy": "none"
          },
          {
            "name": "ISO Week Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6bd16484-b45b-4875-a050-fa478daf920d",
            "sourceColumn": "ISO Week Number",
            "summarizeBy": "sum"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "levels": [
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "e193a8a2-84e1-48f4-80fd-37e341c33a4d",
                "ordinal": 1
              },
              {
                "name": "Calendar Year",
                "column": "Calendar Year",
                "lineageTag": "03e1c6f2-a63e-4df1-97d9-5d7aca3e8052",
                "ordinal": 0
              },
              {
                "name": "Date",
                "column": "Date",
                "lineageTag": "cc9f0871-6214-4d51-8030-84af78f682ad",
                "ordinal": 2
              }
            ],
            "lineageTag": "d1ca48f9-5248-4890-b2a5-bc1b90193c8a"
          }
        ],
        "lineageTag": "15baa3de-6d82-474d-b4e0-9a3b5e5d7166",
        "partitions": [
          {
            "name": "DimDate",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\", \"WideWorldImportersDW\"),",
                "    Dimension_Date = Source{[Schema=\"Dimension\",Item=\"Date\"]}[Data]",
                "in",
                "    Dimension_Date"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimSalesperson",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "EmployeeId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3cc43edb-f426-439c-85aa-450e31a2a232",
            "sourceColumn": "EmployeeId",
            "summarizeBy": "none"
          },
          {
            "name": "WWI Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b4743a40-555c-4f04-8390-f0a600d9ce2e",
            "sourceColumn": "WWI Employee ID",
            "summarizeBy": "count"
          },
          {
            "name": "Is Salesperson",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "d9186219-d36f-4436-98f3-8761917a3ed7",
            "sourceColumn": "Is Salesperson",
            "summarizeBy": "none"
          },
          {
            "name": "Valid From",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "589cebd6-3b1a-4223-a822-896e27ce6c12",
            "sourceColumn": "Valid From",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_32b131e5-4c2b-49d3-ba8f-7c933e2a392b"
                },
                "isDefault": true,
                "relationship": "b290de8a-947f-4bf9-9384-e371c92cb478"
              }
            ]
          },
          {
            "name": "Valid To",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "19463caf-f215-4a65-a143-fced820ceae3",
            "sourceColumn": "Valid To",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_d5321435-4ae4-4c92-9cac-e8572d377201"
                },
                "isDefault": true,
                "relationship": "76c1524e-de7a-47d0-8baf-c1ab0921f469"
              }
            ]
          },
          {
            "name": "First Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "28cc808c-4d13-4c92-8b78-6e14ef5bb86e",
            "sourceColumn": "First Name",
            "summarizeBy": "none"
          },
          {
            "name": "Last Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8806f6e4-d747-41e5-ad9d-028cf9e75354",
            "sourceColumn": "Last Name",
            "summarizeBy": "none"
          },
          {
            "name": "SalesPerson",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "518bee21-8159-4c3d-bc6e-2cdf5f246b63",
            "sourceColumn": "SalesPerson",
            "summarizeBy": "none"
          },
          {
            "name": "JobTitle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c74241f1-fec7-49d5-9a8f-8e3fdac7fa92",
            "sourceColumn": "JobTitle",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce45fd63-23cc-4dad-95c8-dbad0e183985",
            "sourceColumn": "BusinessUnit",
            "summarizeBy": "none"
          },
          {
            "name": "Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "537a02af-1337-490c-8a6e-24bb241f87af",
            "sourceColumn": "Age",
            "summarizeBy": "sum"
          },
          {
            "name": "EmailAddress",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "DimSalesperson[First Name] & \".\" & DimSalesperson[Last Name] & \"@wwi.com\"",
            "isDataTypeInferred": true,
            "lineageTag": "982f1b11-97cf-4edc-b3e1-5e442446f3ca",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "9a0249e4-ff54-4627-9adf-ee038ab9fa8b",
        "partitions": [
          {
            "name": "DimSalesperson",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\", \"WideWorldImportersDW\"),",
                "    Dimension_Employee = Source{[Schema=\"Dimension\",Item=\"Employee\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(Dimension_Employee, each ([Is Salesperson] = true)),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"Preferred Name\", \"Photo\", \"Lineage Key\", \"Fact.Order(Employee Key)\", \"Fact.Order(Employee Key) 2\", \"Fact.Sale\"}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Removed Columns\", \"Employee\", Splitter.SplitTextByDelimiter(\" \", QuoteStyle.Csv), {\"Employee.1\", \"Employee.2\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"Employee.1\", type text}, {\"Employee.2\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Employee.1\", \"First Name\"}, {\"Employee.2\", \"Last Name\"}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns\", \"SalesPerson\", each [First Name] & \" \" & [Last Name]),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Added Custom\", {\"WWI Employee ID\"}, Employee_csv, {\"WWI Employee ID\"}, \"Employee_csv\", JoinKind.LeftOuter),",
                "    #\"Expanded Employee_csv\" = Table.ExpandTableColumn(#\"Merged Queries\", \"Employee_csv\", {\"JobTitle\", \"BusinessUnit\", \"Age\"}, {\"JobTitle\", \"BusinessUnit\", \"Age\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Expanded Employee_csv\",{{\"Employee Key\", \"EmployeeId\"}})",
                "in",
                "    #\"Renamed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_32b131e5-4c2b-49d3-ba8f-7c933e2a392b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7ed6301d-aaeb-457c-8aa3-ff5f9e5d02e7",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "b252cbd9-d2a7-4c4f-984d-c17cb3843dce",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "745e57c4-61bb-4aef-8a31-06fa78cc795d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "a2bcd8fc-b3b6-4868-8936-e09a58589099",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "c034869b-219b-4bb8-891b-e397d456de44",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "eb529662-865a-40a0-9b99-d9754b383d29",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "cef9516a-1f2b-4540-a372-a75f74ec26df",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "b1ee3f67-7477-4fdc-9faa-1c80ef68b060",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a4c89c34-6c10-468e-91b3-11d796e4da5c",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "0ee98dd9-aa2e-47f1-80eb-9fb6b1e25fe4",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "606990af-ddb9-4437-a010-3bddc96cc07b",
                "ordinal": 3
              }
            ],
            "lineageTag": "09bdf9eb-5ff8-4a4b-8c0c-75114adc9290"
          }
        ],
        "isHidden": true,
        "lineageTag": "1f2ffc52-3f12-4f1b-b99f-ffa598c88d82",
        "partitions": [
          {
            "name": "LocalDateTable_32b131e5-4c2b-49d3-ba8f-7c933e2a392b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DimSalesperson'[Valid From])), 1, 1), Date(Year(MAX('DimSalesperson'[Valid From])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_d5321435-4ae4-4c92-9cac-e8572d377201",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1cee85a8-0bf9-46ea-a761-9a6923b6371b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "1c021720-df11-4dab-a3ac-d55ed295ca72",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "e96c7ee2-dc36-460c-ab7b-26e1feacceca",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "fea760b6-e5dc-44a1-adcc-3e896b4f5542",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "f13d6d95-8093-44b6-9138-16cb801ba76f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "97dc8299-ea7f-45af-8f0f-c35b2ad37d32",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "db379912-5fc3-4da6-99e2-0d0418d490d1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "fa4424c2-41f7-4d0d-be39-02c1ec9a6980",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "acb872a1-828c-4c5d-80f3-973c025501c2",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "f0c10fee-7a6b-4436-a20c-9aefb1713219",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "72b3fa4a-7bc5-4976-8557-66b2f2c79a7f",
                "ordinal": 3
              }
            ],
            "lineageTag": "e7cc1187-b594-444b-bdef-856bf39a58de"
          }
        ],
        "isHidden": true,
        "lineageTag": "a20839cf-7c56-447a-bd94-cec519cfed36",
        "partitions": [
          {
            "name": "LocalDateTable_d5321435-4ae4-4c92-9cac-e8572d377201",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DimSalesperson'[Valid To])), 1, 1), Date(Year(MAX('DimSalesperson'[Valid To])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "DimProduct",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Stock Item Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1a8c7b18-6f98-476f-981d-82693074d6e0",
            "sourceColumn": "Stock Item Key",
            "summarizeBy": "none"
          },
          {
            "name": "WWI Stock Item ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a893b731-eefb-40b3-b062-1a62e7a8d317",
            "sourceColumn": "WWI Stock Item ID",
            "summarizeBy": "none"
          },
          {
            "name": "Stock Item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c85cd342-0f58-45a6-871c-346511628dc4",
            "sourceColumn": "Stock Item",
            "summarizeBy": "none"
          },
          {
            "name": "Color",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0becab71-0a77-47e0-bdc8-da5e3b6c4a38",
            "sourceColumn": "Color",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f65381c9-6940-4f18-9b6c-36cd7449f04a",
            "sourceColumn": "Unit Price",
            "summarizeBy": "none"
          },
          {
            "name": "Recommended Retail Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "50bd3db2-fced-4147-adeb-c55a7b023ccc",
            "sourceColumn": "Recommended Retail Price",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb85714d-8710-4d54-80f9-22482cac97fa",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Background Color Format",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Formatting",
            "lineageTag": "0e05488b-8fd8-4f28-b872-f1fe9d4c40ea",
            "sourceColumn": "Background Color Format",
            "summarizeBy": "none"
          },
          {
            "name": "Font Color Format",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Formatting",
            "lineageTag": "319564a8-e19d-497c-aeba-c468b0c90b2a",
            "sourceColumn": "Font Color Format",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "Category Hierarchy",
            "levels": [
              {
                "name": "Category",
                "column": "Category",
                "lineageTag": "0e0b074a-d9ed-4a22-9fea-829db63f0856",
                "ordinal": 0
              },
              {
                "name": "Stock Item",
                "column": "Stock Item",
                "lineageTag": "04ad1801-f41d-49b0-94c3-526b54987efc",
                "ordinal": 1
              }
            ],
            "lineageTag": "11c71499-7d90-46c1-af6a-8da6c0944288"
          }
        ],
        "lineageTag": "e09b61a3-3e79-4f12-8888-aee57e93e751",
        "partitions": [
          {
            "name": "DimProduct",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\", \"WideWorldImportersDW\"),",
                "    #\"Dimension_Stock Item\" = Source{[Schema=\"Dimension\",Item=\"Stock Item\"]}[Data],",
                "    #\"Removed Top Rows\" = Table.Skip(#\"Dimension_Stock Item\",1),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Removed Top Rows\",{\"Stock Item Key\", \"WWI Stock Item ID\", \"Stock Item\", \"Color\", \"Buying Package\", \"Selling Package\", \"Brand\", \"Size\", \"Lead Time Days\", \"Quantity Per Outer\", \"Is Chiller Stock\", \"Barcode\", \"Tax Rate\", \"Unit Price\", \"Recommended Retail Price\", \"Typical Weight Per Unit\", \"Photo\", \"Valid From\", \"Valid To\", \"Lineage Key\", \"Fact.Movement\", \"Fact.Order\", \"Fact.Purchase\", \"Fact.Sale\", \"Fact.Stock Holding\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Reordered Columns\",{\"Buying Package\", \"Selling Package\", \"Brand\", \"Size\", \"Lead Time Days\", \"Quantity Per Outer\", \"Is Chiller Stock\", \"Barcode\", \"Tax Rate\", \"Typical Weight Per Unit\", \"Photo\", \"Valid From\", \"Valid To\", \"Lineage Key\", \"Fact.Movement\", \"Fact.Order\", \"Fact.Purchase\", \"Fact.Sale\", \"Fact.Stock Holding\"}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Removed Columns\", {\"Stock Item\"}, DimCategory, {\"Description\"}, \"Dimension Category\", JoinKind.LeftOuter),",
                "    #\"Expanded Dimension Category\" = Table.ExpandTableColumn(#\"Merged Queries\", \"Dimension Category\", {\"Category\"}, {\"Category\"}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Expanded Dimension Category\", {\"Color\"}, #\"Color Formats\", {\"Color\"}, \"Color Formats\", JoinKind.LeftOuter),",
                "    #\"Expanded Color Formats\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"Color Formats\", {\"Background Color Format\", \"Font Color Format\"}, {\"Background Color Format\", \"Font Color Format\"})",
                "in",
                "    #\"Expanded Color Formats\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FactSale",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Sale Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "08f82827-7563-4398-bcf6-a8cb0d805b62",
            "sourceColumn": "Sale Key",
            "summarizeBy": "count"
          },
          {
            "name": "City Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "38e2733a-5888-4b7f-b202-94e457de66cb",
            "sourceColumn": "City Key",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bd1e458e-0eb0-44e8-99f5-e246062a0017",
            "sourceColumn": "Customer Key",
            "summarizeBy": "count"
          },
          {
            "name": "Invoice Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ad0e77b2-b611-4e85-9f6b-7c0a340fd7e3",
            "sourceColumn": "Invoice Date",
            "summarizeBy": "none"
          },
          {
            "name": "Delivery Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "608c0a19-6fd7-4dfe-9bd6-86038c83925b",
            "sourceColumn": "Delivery Date",
            "summarizeBy": "none"
          },
          {
            "name": "Salesperson Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "abbbfd26-274d-45ae-b9ea-b1a87581cc29",
            "sourceColumn": "Salesperson Key",
            "summarizeBy": "none"
          },
          {
            "name": "WWI Invoice ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f6a66850-1c55-4498-8069-7e28d72a2f2d",
            "sourceColumn": "WWI Invoice ID",
            "summarizeBy": "count"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "33dbd3e4-7e19-4f77-ab26-1a455850f150",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "double",
            "formatString": "0.00",
            "lineageTag": "860904b3-4983-4f48-ba15-bac2369aace9",
            "sourceColumn": "Unit Price",
            "summarizeBy": "average"
          },
          {
            "name": "Tax Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f213b7b2-4e52-44cc-8ad4-c9b69609d4cd",
            "sourceColumn": "Tax Rate",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Excluding Tax",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a67e18fb-f981-4dbb-b6e9-a4907f4ef798",
            "sourceColumn": "Total Excluding Tax",
            "summarizeBy": "sum"
          },
          {
            "name": "Tax Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cd1c95e2-c5ab-49e1-8599-2ed5524e4028",
            "sourceColumn": "Tax Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Profit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "441683ee-d1ea-4f6d-a697-2f720357f65b",
            "sourceColumn": "Profit",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Including Tax",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "description": [
              "Standard Tax",
              ""
            ],
            "lineageTag": "ba6e3485-8b7e-43e4-a161-d11bf3a5352d",
            "sourceColumn": "Total Including Tax",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Dry Items",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "17e592b1-ccc7-46b2-8b53-0adceaeed3cf",
            "sourceColumn": "Total Dry Items",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Chiller Items",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9f94b3bb-cb4d-4b2c-880c-30bc47db9bad",
            "sourceColumn": "Total Chiller Items",
            "summarizeBy": "sum"
          },
          {
            "name": "Profit case",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c982b65-327d-412e-b0ac-aa0704bcd559",
            "sourceColumn": "Profit case",
            "summarizeBy": "none"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d3d4ae87-56f0-4f15-aa91-b9a0366265bd",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          },
          {
            "name": "Package",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ee6af2c-8d12-437a-b956-42dfb77f2fbb",
            "sourceColumn": "Package",
            "summarizeBy": "none"
          },
          {
            "name": "Stock Item Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "89c6763b-ea9c-48e8-b6c8-c73faa8c6773",
            "sourceColumn": "Stock Item Key",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7206e440-0f50-4849-a95b-555e62671212",
        "measures": [
          {
            "name": "Cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "SUM('FactSale'[Total Excluding Tax]) - SUM('FactSale'[Profit])"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "MathematicalSubtraction",
                  "version": 0
                }
              }
            ],
            "lineageTag": "7d728960-5530-48d9-adb5-82d9c5a9b736"
          },
          {
            "name": "ProfitMargin",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "DIVIDE(SUM('FactSale'[Profit]), SUM('FactSale'[Total Excluding Tax]))"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "MathematicalDivision",
                  "version": 0
                }
              }
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "cbc0cc78-0a4c-439e-944b-d2e985d1048f"
          }
        ],
        "partitions": [
          {
            "name": "FactSale",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"localhost\", \"WideWorldImportersDW\"),",
                "    Fact_Sale = Source{[Schema=\"Fact\",Item=\"Sale\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(Fact_Sale,{\"Bill To Customer Key\", \"Stock Item Key\"}),",
                "    #\"Expanded Dimension.Stock Item\" = Table.ExpandRecordColumn(#\"Removed Columns\", \"Dimension.Stock Item\", {\"Stock Item Key\"}, {\"Dimension.Stock Item.Stock Item Key\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Expanded Dimension.Stock Item\",{{\"Dimension.Stock Item.Stock Item Key\", \"Stock Item Key\"}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Renamed Columns1\",{{\"Invoice Date Key\", \"Invoice Date\"}, {\"Delivery Date Key\", \"Delivery Date\"}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Renamed Columns\", \"Profit case\", each if [Profit] > 0 then \"Positive\" else \"Negative\"),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Added Conditional Column\",{\"Lineage Key\", \"Dimension.City\", \"Dimension.Customer(Bill To Customer Key)\", \"Dimension.Customer(Customer Key)\", \"Dimension.Date(Delivery Date Key)\", \"Dimension.Date(Invoice Date Key)\", \"Dimension.Employee\"})",
                "in",
                "    #\"Removed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimTarget",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b8b92194-c01f-4bcf-baf1-312542ce938b",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "EmployeeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8f2c3a1f-c2ce-40b1-ae03-db0307aedb4d",
            "sourceColumn": "EmployeeID",
            "summarizeBy": "none"
          },
          {
            "name": "MonthNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bdd6efbc-5cd2-494c-b006-57ab40c5e0d2",
            "sourceColumn": "MonthNumber",
            "summarizeBy": "sum"
          },
          {
            "name": "TargetMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "205f3f3d-dee2-4f7d-90ac-79158c381303",
            "sourceColumn": "TargetMonth",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "86515d8d-75c3-4af6-94e9-1cd22e39085d",
            "sourceColumn": "Value",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "5d9d7c53-8bb9-4737-bfd8-393ab04ef6e4",
        "partitions": [
          {
            "name": "DimTarget",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\janek\\OneDrive\\Pulpit\\PowerBI\\Lab - dane-20241009\\Dodatkowe dane\\SalespersonTargets.csv\"),[Delimiter=\";\", Columns=14, Encoding=1250, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Year\", Int64.Type}, {\"EmployeeID\", Int64.Type}, {\"M01\", Int64.Type}, {\"M02\", Int64.Type}, {\"M03\", Int64.Type}, {\"M04\", Int64.Type}, {\"M05\", Int64.Type}, {\"M06\", Int64.Type}, {\"M07\", Int64.Type}, {\"M08\", Int64.Type}, {\"M09\", Int64.Type}, {\"M10\", Int64.Type}, {\"M11\", Int64.Type}, {\"M12\", Int64.Type}}),",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Changed Type\", {\"Year\", \"EmployeeID\"}, \"Attribute\", \"Value\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Unpivoted Other Columns\",{{\"Attribute\", \"MonthNumber\"}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns\",\"M\",\"\",Replacer.ReplaceText,{\"MonthNumber\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Replaced Value\",{{\"MonthNumber\", Int64.Type}}),",
                "    #\"Multiplied Column\" = Table.TransformColumns(#\"Changed Type1\", {{\"Value\", each _ * 1000, type number}}),",
                "    #\"Added Custom Column\" = Table.AddColumn(#\"Multiplied Column\", \"Custom\", each Text.Combine({Text.PadStart(Text.From([MonthNumber], \"pl-PL\"), 2, \"0\"), \".\", Text.From([Year], \"pl-PL\")}), type text),",
                "    #\"Parsed Date\" = Table.TransformColumns(#\"Added Custom Column\",{{\"Custom\", each Date.From(DateTimeZone.From(_)), type date}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Parsed Date\",{{\"Custom\", \"TargetMonth\"}}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Renamed Columns1\",{\"EmployeeID\", \"Year\", \"MonthNumber\", \"TargetMonth\", \"Value\"})",
                "in",
                "    #\"Reordered Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Employee_csv",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "WWI Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9ef7a8ce-6980-47e5-896b-94a60bbb0663",
            "sourceColumn": "WWI Employee ID",
            "summarizeBy": "count"
          },
          {
            "name": "Employee",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bcb5833d-2437-4e9b-8f30-dc59f71b3bee",
            "sourceColumn": "Employee",
            "summarizeBy": "none"
          },
          {
            "name": "JobTitle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6209c18e-aff0-4ee9-8c33-e9578919fcbb",
            "sourceColumn": "JobTitle",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7dacce3f-d72a-4426-9397-c272297e5315",
            "sourceColumn": "BusinessUnit",
            "summarizeBy": "none"
          },
          {
            "name": "Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3173f7a0-531c-4de0-a6cf-9403dbc14f52",
            "sourceColumn": "Age",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "6e548a9d-c639-417f-a8ab-6bd6d750a2b5",
        "partitions": [
          {
            "name": "Employee_csv",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\janek\\OneDrive\\Pulpit\\PowerBI\\Lab - dane-20241009\\Dodatkowe dane\\Employee_csv.csv\"),[Delimiter=\";\", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"WWI Employee ID\", Int64.Type}, {\"Employee\", type text}, {\"JobTitle\", type text}, {\"BusinessUnit\", type text}, {\"Age\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimCategory",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "WWI Stock Item ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1548d06c-fe76-46a1-8872-f3dc8380eeeb",
            "sourceColumn": "WWI Stock Item ID",
            "summarizeBy": "count"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "41f2c9b6-fd5c-4b8d-b829-3cbed753886a",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4a447f87-c5bc-48d2-82fe-fa1e8c12b22a",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "288afc1c-d6c7-427e-bc19-32214556ab77",
        "partitions": [
          {
            "name": "DimCategory",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\janek\\OneDrive\\Pulpit\\PowerBI\\Lab - dane-20241009\\Dodatkowe dane\\Category_dictionary.xlsx\"), null, true),",
                "    Arkusz1_Sheet = Source{[Item=\"Arkusz1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Arkusz1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"WWI Stock Item ID\", Int64.Type}, {\"Description\", type text}, {\"Category\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Measures",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f5a46a87e38f4ead9cf47079a5154cb3"
          },
          {
            "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
            "value": "{\"Expression\":\"\"}"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e82e237c-e3b1-4476-ae4b-e1ae84894808",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "aef29589-94ba-4152-8a7d-e5fcfa8be257",
        "measures": [
          {
            "name": "Total Net Sales",
            "expression": "SUM(FactSale[Total Excluding Tax])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a82b5119-1980-4915-ab0d-cc12777f79bb"
          },
          {
            "name": "Average Price",
            "displayFolder": "Pricing",
            "expression": "AVERAGE(FactSale[Unit Price])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "9acce8c9-a2dd-44c1-ad58-2c35b58ceaf6"
          },
          {
            "name": "Total Profit",
            "expression": "SUM(FactSale[Profit])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "5a1ddfb5-03a1-4321-bc79-62bd75ef3e5e"
          },
          {
            "name": "Profit Margin",
            "expression": "DIVIDE([Total Profit], [Total Net Sales])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "7f3bec23-b6b6-45ac-b9cc-ed504a0c7492"
          },
          {
            "name": "Max Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Pricing",
            "expression": "MAX(FactSale[Unit Price])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "c0713332-e01a-4f5a-9cea-a6630689f333"
          },
          {
            "name": "Min Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Pricing",
            "expression": "MIN(FactSale[Unit Price])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "d3988071-fb57-4d27-9c12-6dcc03037011"
          },
          {
            "name": "Median Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Pricing",
            "expression": "MEDIAN(FactSale[Unit Price])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "55248bbe-12de-4896-b453-55039c1247b1"
          },
          {
            "name": "Sales 2014",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Sales Filtered",
            "expression": "CALCULATE([Total Net Sales], 'DimDate'[Calendar Year] = 2014)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "b844ea54-dcab-4f8e-9c39-4c55e6e9939d"
          },
          {
            "name": "Sales Above 5000",
            "displayFolder": "Sales Filtered",
            "expression": "CALCULATE([Total Net Sales], FILTER('FactSale', [Total Excluding Tax] > 5000))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "202a8298-a9d8-4c64-a23b-b359702a20ae"
          },
          {
            "name": "Sales Packaging Materials",
            "displayFolder": "Sales Filtered",
            "expression": "CALCULATE([Total Net Sales], FILTER('DimProduct', [Category] = \"Packaging Materials\"))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "f2513b70-44ec-42a9-bf8f-c3f0e6395527"
          },
          {
            "name": "YTD Total Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "YTD Total Sales",
            "expression": "TOTALYTD([Total Net Sales], 'DimDate'[Date])",
            "lineageTag": "bb4de7a5-7410-45ad-80a2-c008213806ea"
          },
          {
            "name": "YTD-1 Total Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "YTD Total Sales",
            "expression": "CALCULATE([YTD Total Sales], SAMEPERIODLASTYEAR('DimDate'[Date]))",
            "lineageTag": "c6797fad-0b47-4f9b-9aaf-99d426c60c74"
          },
          {
            "name": "YTD vs YTD-1 Total Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "YTD Total Sales",
            "expression": "[YTD Total Sales] - [YTD-1 Total Sales]",
            "lineageTag": "51c8773a-3036-428e-9ca5-b623fdd9422f"
          },
          {
            "name": "YTD vs YTD-1 Total Sales %",
            "displayFolder": "YTD Total Sales",
            "expression": "DIVIDE([YTD vs YTD-1 Total Sales], [YTD-1 Total Sales], 1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "fca47f63-3aab-42f7-b097-2ebf90b51141"
          },
          {
            "name": "Total Quantity",
            "expression": "SUM('FactSale'[Quantity])",
            "formatString": "0",
            "lineageTag": "4233e5d8-ed36-4cef-be1f-45da2b3a8eff"
          },
          {
            "name": "YTD Total Quantity",
            "displayFolder": "YTD Total Quantity",
            "expression": "TOTALYTD([Total Quantity], 'DimDate'[Date])",
            "formatString": "0",
            "lineageTag": "057302fc-ab9e-441d-abf6-fa69696c727e"
          },
          {
            "name": "YTD-1 Total Quantity",
            "displayFolder": "YTD Total Quantity",
            "expression": "CALCULATE([YTD Total Quantity], SAMEPERIODLASTYEAR('DimDate'[Date]))",
            "formatString": "0",
            "lineageTag": "5b1ee205-d616-427a-b674-4386d1f26bb3"
          },
          {
            "name": "YTD vs YTD-1 Total Quantity",
            "displayFolder": "YTD Total Quantity",
            "expression": "[YTD Total Quantity] - [YTD-1 Total Quantity]",
            "formatString": "0",
            "lineageTag": "78fe275e-6445-4ce1-b51a-2f1241045945"
          },
          {
            "name": "YTD vs YTD-1 Total Quantity %",
            "displayFolder": "YTD Total Quantity",
            "expression": "DIVIDE([YTD vs YTD-1 Total Quantity], [YTD-1 Total Quantity], 1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "9e53176b-a863-4d7f-b715-a7fe28f3dc26"
          },
          {
            "name": "Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pl-PL\"}"
              }
            ],
            "expression": "SUM(DimTarget[Value])",
            "formatString": "#,0\\ \"z\";-#,0\\ \"z\";#,0\\ \"z\"",
            "lineageTag": "c2d8cbfc-e2ac-45c8-874a-d2eccc8bd2c2"
          },
          {
            "name": "Target YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pl-PL\"}"
              }
            ],
            "expression": "TOTALYTD([Target], DimDate[Date])",
            "formatString": "#,0\\ \"z\";-#,0\\ \"z\";#,0\\ \"z\"",
            "lineageTag": "b3c53048-5820-4a3b-9492-367424fc7b3b"
          },
          {
            "name": "SalesTargetYTDDiff",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pl-PL\"}"
              }
            ],
            "expression": "[YTD Total Sales] - [Target YTD]",
            "formatString": "#,0\\ \"z\";-#,0\\ \"z\";#,0\\ \"z\"",
            "lineageTag": "2446ed93-4947-4a2c-bc8d-fb185cb1050f"
          },
          {
            "name": "SalesTargetYTDDiff %",
            "expression": "DIVIDE([SalesTargetYTDDiff], [YTD Total Sales])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "dd925ff4-9f5c-4096-b3fc-159cf3cb03ae"
          }
        ],
        "partitions": [
          {
            "name": "_Measures",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Dates_1",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "bc759d1524a34554ba05215babfd2027"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f65d0a8e-3dc9-4181-93b7-b5f084241073",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_2e833427-8579-4df0-8f16-4a674172c644"
                },
                "isDefault": true,
                "relationship": "4cd6e21e-0887-4c2e-86e0-2021c5775ba0"
              }
            ]
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR('Dates_1'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "84879fdc-4150-4f39-873d-1c2a6e0a680d",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "MONTH('Dates_1'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "dee6e186-ac5b-4ef1-8551-365a00063e96",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "MonthName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Dates_1'[Date], \"mmm\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ba9f956e-4242-43fc-8243-0d7f0a4a6ada",
            "sortByColumn": "Month",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "FiscalYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "\"FY\" & YEAR('Dates_1'[Date]) + IF(MONTH('Dates_1'[Date]) > 6, 1)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "bb3f1ff2-6030-40e0-a1cd-13c2a679d685",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "(YEAR('Dates_1'[Date]) * 100) + MONTH('Dates_1'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1bd3b2a9-6363-4611-b321-40415571566b",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "37f6508a-e242-422f-be56-8e4c91a72a13",
        "partitions": [
          {
            "name": "Dates_1",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(DATE(2022, 1, 1), DATE(2024, 1, 1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_2e833427-8579-4df0-8f16-4a674172c644",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "559acce4-24ad-4bd6-87a5-e292801eaf6d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "6b8b518d-e6d7-453f-8775-6e50613fc27d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "d82d0b32-0051-4586-b17a-1a4bfbe296d4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "f41f18ec-7345-4ede-8622-7bca2802caa6",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "8db963da-81ef-4120-bfad-003fd29801df",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "a7156b8d-e7c8-4595-947f-7907912f383b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "5367f1de-84a5-4ed8-898e-a92bcfdf9ec6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "b0084806-06ac-4310-94aa-b734191baf0f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d4c4611b-c0fd-4353-9f38-d2dbf667b513",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "1d65b9ff-44f1-4958-80ff-c5d41d621033",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f770e463-671c-4363-a084-48b9709f2bcb",
                "ordinal": 3
              }
            ],
            "lineageTag": "47d295f6-c793-4620-b0c4-44c7e6664185"
          }
        ],
        "isHidden": true,
        "lineageTag": "c73f51d5-97a2-4c08-91b5-8a0e9626b2ca",
        "partitions": [
          {
            "name": "LocalDateTable_2e833427-8579-4df0-8f16-4a674172c644",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Dates_1'[Date])), 1, 1), Date(Year(MAX('Dates_1'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}